### ISSUE TITLE
application.properties empty

### ISSUE THREAD

**Issue by dcpc007** [Lurkars/ghs-server#27]
Hello /  Bonjour

## Case 
I try to install a version for my group on a VPS.

i run a docker-compose file to mount a local folder to be able to edit parameters, application starts, i see the sqllite file and application.properties, but this one is empty (0 byte).

I run temporary with basic docker start and inside the container, the application.properties is empty too.

The doc says to overwrite the properties. Did i miss something ?
Should we create manually all lines ?

## Additional infos 
When i try to reach on my browser (http://dns:port) i have noclient.html page -->

Gloomhaven Secretariat Server
Server is running. No client installed. If you want to serve client, see [Instructions](https://github.com/Lurkars/ghs-server#serve-client).

**Comment by dcpc007** [comment]
For info too, i try to create this docker-compose.yml

```
version: '3'

services:
  ghs-server:
    image: gloomhavensecretariat/ghs-server
    ports:
      - "3382:8080"
    environment:
      - TZ=Europe/Paris
    restart: unless-stopped
    volumes:
      - /srv/ghs-server/ghs:/root/.ghs
```
